### ISSUE TITLE
what is the data format？

### ISSUE THREAD

**Issue by chzeze** [UKPLab/naacl18-multitask_argument_mining#2]
Could you shared the Data?

**Comment by SteffenEger** [comment]
I think the *data format* is simply tab separated format. E.g. column 0 is token, column 1 is label. I.e., it looks similar like this here:
 https://raw.githubusercontent.com/UKPLab/acl2017-neural_end2end_am/master/data/conll/Paragraph_Level/train.dat, but without the unnecessary columns (also, the labels are only BIO+type, rather than additionally the relations)

Concerning the individual datasets: `essays` is the dataset linked above. I'm not sure if we are allowed to share the others. We'll solve this in the next weeks.

**Comment by daxenberger** [comment]
BTW: all data is online now. 
https://github.com/UKPLab/naacl18-multitask_argument_mining/tree/master/dataSplits

**Comment by chzeze** [comment]
Thanks
